version: '3.8' # Nên thêm version để tránh cảnh báo của Docker

services:
  # 1. Database MySQL
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root         # Đã đồng bộ với Python
      MYSQL_DATABASE: web_store         # Đã đồng bộ với Python
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Tự động chạy script tạo DB
    networks:
      - noah-network

  # 2. Database PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      # Ánh xạ file khởi tạo để tự động tạo bảng transactions
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - noah-network

  # 3. Dịch vụ Report
  report_service:
    build: ./report_service
    ports:
      - "8005:8000"
    depends_on:
      - mysql-db
      - postgres
    networks:
      - noah-network

  # 4. Dịch vụ Legacy Adapter 
  legacy-adapter:
    build: ./legacy_adapter
    depends_on:
      - mysql-db
    environment:                 # <--- Thêm dòng này
      - PYTHONUNBUFFERED=1
    volumes:
      - ./legacy_adapter/input:/app/input       # Ánh xạ thư mục input
      - ./legacy_adapter/processed:/app/processed # Ánh xạ thư mục processed
    networks:
      - noah-network

  # 5. Kong Gateway
  kong:
    image: kong:3.4.0
    container_name: kong_gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    volumes:
      - ./gateway/kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - noah-network

networks:
  noah-network:
    driver: bridge